FROM python:3.12-slim

# Install system dependencies
RUN apt-get update && apt-get install -y gcc libpq-dev && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Install your application in development mode
COPY . .
COPY setup.py .
RUN pip install -e . --no-deps

CMD ["dagster-webserver", "-w", "dagster_files/workspace.yaml", "-h", "0.0.0.0", "-p", "3000"]
