apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAZGI6NTQzMi9oZWFsdGhfZGF0YQ==
  DAGSTER_PG_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAZGI6NTQzMi9oZWFsdGhfZGF0YT9vcHRpb25zPS1jJTIwc2VhcmNoX3BhdGglM0RkYWdzdGVyX21ldGFkYXRh
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  PGADMIN_DEFAULT_PASSWORD: YWRtaW4=
