apiVersion: apps/v1
kind: Deployment
metadata:
  name: dagster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dagster
  template:
    metadata:
      labels:
        app: dagster
    spec:
      containers:
      - name: dagster
        image: dagster:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: app-config
        - secretRef:
            name: app-secrets

---

apiVersion: v1
kind: Service
metadata:
  name: dagster-service
spec:
  selector:
    app: dagster
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30030
  type: NodePort
