"""create patient_biometric_hourly_summary table

Revision ID: 0e45a3581a53
Revises: 8e98a16e8c3c
Create Date: 2025-05-30 17:23:10.081774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e45a3581a53'
down_revision: Union[str, None] = '8e98a16e8c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_biometric_hourly_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('biometric_type', sa.String(), nullable=False),
    sa.Column('hour_start', sa.DateTime(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('avg_value', sa.Float(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'biometric_type', 'hour_start', name='uix_patient_type_hour')
    )
    op.create_index(op.f('ix_patient_biometric_hourly_summary_biometric_type'), 'patient_biometric_hourly_summary', ['biometric_type'], unique=False)
    op.create_index(op.f('ix_patient_biometric_hourly_summary_hour_start'), 'patient_biometric_hourly_summary', ['hour_start'], unique=False)
    op.create_index(op.f('ix_patient_biometric_hourly_summary_id'), 'patient_biometric_hourly_summary', ['id'], unique=False)
    op.create_index(op.f('ix_patient_biometric_hourly_summary_patient_id'), 'patient_biometric_hourly_summary', ['patient_id'], unique=False)
    op.drop_constraint(op.f('unique_biometric_entry'), 'biometrics', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('unique_biometric_entry'), 'biometrics', ['patient_id', 'biometric_type', 'systolic', 'diastolic', 'value', 'unit', 'timestamp'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_patient_biometric_hourly_summary_patient_id'), table_name='patient_biometric_hourly_summary')
    op.drop_index(op.f('ix_patient_biometric_hourly_summary_id'), table_name='patient_biometric_hourly_summary')
    op.drop_index(op.f('ix_patient_biometric_hourly_summary_hour_start'), table_name='patient_biometric_hourly_summary')
    op.drop_index(op.f('ix_patient_biometric_hourly_summary_biometric_type'), table_name='patient_biometric_hourly_summary')
    op.drop_table('patient_biometric_hourly_summary')
    # ### end Alembic commands ###
